version: '3'
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'denis'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'laravel_vue_proj'
            MYSQL_USER: 'denis'
            MYSQL_PASSWORD: 'denis'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'lar-proj-mysql:/var/lib/mysql'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 3330:80
        environment:
            PMA_ARBITRARY: 1
volumes:
    lar-proj-mysql:
        driver: local
